[package]
name = "prodash"
version = "7.0.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
description = "A dashboard for visualizing progress of asynchronous and possibly blocking tasks"
edition = "2018"
include = ["src/**/*", "README.md", "LICENSE.md", "CHANGELOG.md"]
license = "MIT"
repository = "https://github.com/Byron/prodash"
readme = "README.md"

[lib]
doctest = true

[[example]]
name = "dashboard"
path = "examples/dashboard.rs"
required-features = ["tui-renderer", "tui-renderer-crossterm", "line-renderer", "line-renderer-crossterm"]

[features]
default = ["log-renderer", "localtime"]
tui-renderer-termion = ["crosstermion/tui-react-termion"]
tui-renderer-crossterm = ["crosstermion/tui-react-crossterm"]
tui-renderer = ["tui",
                "unicode-segmentation",
                "unicode-width",
                "crosstermion/input-async",
                "tui-react",
                "futures-util",
                "futures-core",
                "smol",
                "humantime"]
line-renderer = ["flume", "ansi_term"]
line-renderer-crossterm = ["crosstermion/crossterm"]
line-renderer-termion = ["crosstermion/termion"]
log-renderer = ["log"]
localtime = ["time"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dashmap = "3.4.3"
parking_lot = "0.11.0"

# with-logging
log = { version = "0.4.8", optional = true }

# tui-renderer
tui = { version = "0.9.4", optional = true, default-features = false }
tui-react = { version = "0.4.0", optional = true }
smol = { version = "0.1.5", optional = true, default-features = false }
futures-core = { version = "0.3.4", optional = true, default-features = false }
futures-util = { version = "0.3.4", optional = true, default-features = false }
unicode-segmentation = { version = "1.6.0", optional = true }
humantime = { version = "2.0.0", optional = true }
unicode-width = { version = "0.1.7", optional = true }
futures-channel = { version = "0.3.5", optional = true }
crosstermion = { version = "0.1.0", path = "crosstermion", optional = true, default-features = false }

# localtime support for tui-renderer
time = { version = "0.2.9", optional = true, features = ["std"], default-features = false }

# line renderer
flume = { version = "0.7.1", optional = true, default-features = false, features = ['select'] }
ansi_term = { version = "0.12.1", optional = true, default-features = false }

[package.metadata.docs.rs]
all-features = true

[dev-dependencies]
rand = "0.7.3"
env_logger = { version = "0.7.1", default-features = false, features = ["termcolor", "atty", "humantime"] }
criterion = { version = "0.3.1", default-features = false }
argh = "0.1.3"
futures = "0.3.5"
atty = "0.2.14"

[[bench]]
name = "usage"
path = "benches/usage.rs"
harness = false

[workspace]
members = ["crosstermion"]
