[package]
name = "prodash"
version = "4.0.3"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
description = "A dashboard for visualizing progress of asynchronous and possibly blocking tasks"
edition = "2018"
include = ["src/**/*", "README.md", "LICENSE.md"]
license = "MIT"
repository = "https://github.com/Byron/prodash"
readme = "README.md"

[lib]
doctest = true

[features]
default = ["tui-renderer", "log-renderer", "localtime"]
tui-renderer = ["tui", "tui-react", "termion", "async-channel", "smol", "futures-util", "futures-core", "unicode-segmentation", "unicode-width", "humantime" ]
log-renderer = ["log"]
localtime = ["time"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dashmap = "3.4.3"
parking_lot = "0.11.0"

# with-logging
log = { version = "0.4.8", optional = true }

# tui-renderer
tui = { version = "0.9.4", optional = true }
tui-react = { version = "0.4.0", optional = true }
smol = { version = "0.1.5", optional = true }
termion = { version = "1.5.5", optional = true }
futures-core = { version = "0.3.4", optional = true, default-features = false }
futures-util = { version = "0.3.4", optional = true, default-features = false }
unicode-segmentation = { version = "1.6.0", optional = true }
humantime = { version = "2.0.0", optional = true }
unicode-width = { version = "0.1.7", optional = true }
async-channel = { version = "1.1.1", optional = true }

# localtime support for tui-renderer
time = { version = "0.2.9", optional = true, features = ["std"], default-features = false }

[dev-dependencies]
rand = "0.7.3"
env_logger = { version = "0.7.1", default-features = false, features = ["termcolor", "atty", "humantime"] }
criterion = "0.3.1"
termion = "1.5.5"
argh = "0.1.3"

[[bench]]
name = "usage"
path = "benches/usage.rs"
harness = false
