[package]
name = "crosstermion"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
description = "The unification of crossterm and termium behind a common facade for use with feature flags"
edition = "2018"
include = ["src/**/*", "README.md", "LICENSE.md"]
license = "MIT"
repository = "https://github.com/Byron/prodash"
readme = "README.md"

[features]
default = []
tui-termion = ["tui", "tui/termion", "termion"]
tui-react-termion = ["tui-react", "tui", "tui/termion", "termion"]
tui-crossterm = ["tui", "tui/crossterm", "crossterm"]
tui-react-crossterm = ["tui-react", "tui", "tui/crossterm", "crossterm"]
async = ["futures-channel", "futures-util", "smol"]

[dependencies]
crossterm = { version = "0.17.5", optional = true, default-features = false }
termion = { version = "1.5.5", optional = true, default-features = false }
futures-channel = { version = "0.3.5", optional = true, default-features = false }
futures-util = { version = "0.3.5", optional = true, default-features = false }
smol = { version = "0.1.18", optional = true, default-features = false }
tui = { version = "0.9.5", optional = true, default-features = false }
tui-react = { version = "0.4.0", optional = true, default-features = false }
